trigger:
  branches:
    include:
    - main
variables:
- group: devflow-main-infra-variable-group  
stages:
- stage: Development
  displayName: Development Stage
  jobs:
  - job: DevelopmentJob
    pool:
      vmImage:  'windows-latest'
    steps:
    # Step 1: Install Terraform
    - task: TerraformInstaller@1
      displayName: "Install Terraform"
      inputs:
        terraformVersion: '1.5.7'  # Specify Terraform version
    # Step 2: Login to azure for proper access to your azure account
    - task: AzureCLI@2
      displayName: "Azure CLI Login"
      inputs:
        azureSubscription: $(terraform-service-connection)
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: |
          echo "Azure CLI logged in"  
    - task: AzureCLI@2
      displayName: "Terraform Init"
      inputs:
        azureSubscription: $(terraform-service-connection)
        scriptType: 'bash'  # Use batch for Windows agent
        scriptLocation: 'inlineScript'
        inlineScript: |
          terraform init \
          -backend-config="storage_account_name=progetsa" \
          -backend-config="container_name=terraform-state" \
          -backend-config="key=project.tfstate" \
          -backend-config="resource_group_name=backend-rg" \
          -backend-config="subscription_id=$(ARM_SUBSCRIPTION_ID)" \
          -backend-config="client_id=$(ARM_CLIENT_ID)" \
          -backend-config="client_secret=$(ARM_CLIENT_SECRET)" \
          -backend-config="tenant_id=$(ARM_TENANT_ID)"  -var subscription_id=$(ARM_SUBSCRIPTION_ID)
    - task: AzureCLI@2
      displayName: "Terraform Plan"
      inputs:
        azureSubscription: $(terraform-service-connection)
        scriptType: 'bash'  # Use batch for Windows agent
        scriptLocation: 'inlineScript'
        inlineScript: |
          export ARM_CLIENT_ID=$(ARM_CLIENT_ID)
          export ARM_CLIENT_SECRET=$(ARM_CLIENT_SECRET)
          export ARM_TENANT_ID=$(ARM_TENANT_ID)
          export ARM_SUBSCRIPTION_ID=$(ARM_SUBSCRIPTION_ID)
          terraform plan -destroy -var subscription_id=$(ARM_SUBSCRIPTION_ID) 
    - task: AzureCLI@2
      displayName: "Terraform Apply"
      inputs:
        azureSubscription: $(terraform-service-connection)
        scriptType: 'bash'  # Use batch for Windows agent
        scriptLocation: 'inlineScript'
        inlineScript: |
          export ARM_CLIENT_ID=$(ARM_CLIENT_ID)
          export ARM_CLIENT_SECRET=$(ARM_CLIENT_SECRET)
          export ARM_TENANT_ID=$(ARM_TENANT_ID)
          export ARM_SUBSCRIPTION_ID=$(ARM_SUBSCRIPTION_ID)
          terraform destroy -var subscription_id=$(ARM_SUBSCRIPTION_ID) -auto-approve
        